#!/usr/bin/env bash
# make_cfengine.sh

# With Ubuntu (Debian) installer you don't need to add /var/cfengine/bin to your $PATH,
# the /var/cfengine/bin/ binaries are automatically symlinked to /usr/local/sbin/ :)
# Also the public-private keypair is auto generated by runnng /var/cfengine/bin/cf-key :)
# Lastly, the /var/cfengine/masterfiles/ directory is auto populated :)
#
# In other words, use the this source to install and only compile if you have to.

# Download and install the CFEngine GPG key.
sudo -s << EOF
wget -qO- http://cfengine.com/pub/gpg.key | apt-key add -
EOF

# Manually add the repository to the sources.list.
sudo sh -c "cat << EOF > /etc/apt/sources.list.d/cfengine-community.list
deb http://cfengine.com/pub/apt/packages stable main
EOF"

# Update the new sources.list, is this needed?
sudo apt-get -q=1 update

# Install the package.
sudo apt-get install -y cfengine-community

# Finally, CFEngine needs to be “bootstrapped.” This means copying the masterfiles
# to their final working location in /var/cfengine/inputs/ and starting the base
# cf-execd daemon. This process controls the periodic execution of cf-agent, which
# is the one that actually executes the promises in the provided policies.
#
# Bootstrap CFEngine, the commercial edition may take a few minutes.
# To check if policy server is running: /var/cfengine/bin/cf-agent --version or use ps ax | grep cf
#
# Make sure to use the correct policy server IP for the --bootstrap option.
# Assume it's 192.168.0.22
# sudo /var/cfengine/bin/cf-agent --bootstrap <server-ip>
